### ISSUE TITLE
Accept PR?

### ISSUE THREAD

**Issue by ncrypthic** [nicovogelaar/protoc-gen-gofullmethods#5]
Hi there,

I fork this repo and update the code using Google's [protogen](https://pkg.go.dev/google.golang.org/protobuf/compiler/protogen) package. Do you want to merge the new code?

Cheers!

**Comment by nicovogelaar** [comment]
Awesome! Thanks @ncrypthic. Yes, that would be great!

**Comment by ncrypthic** [comment]
I just created the PR #6 @nicovogelaar , please have a look.
